server :
  port : 80
spring :
  thymeleaf :
    prefix : views/
    suffix : .html
    cache : false
  datasource :
    driver-class-name : com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/db322
    username : usr322
    password : 123456
    
mybatis :
  type-aliases-package : aaa.model
  configuration :
    map-underscore-to-camel-case : true